### ISSUE TITLE
No results in NaVi viewer

### ISSUE THREAD

**Issue by Jaspermid** [devinit/D-Portal#179]
In the Netherlands we're starting to see a lot more organisations using results. Dor us d-Portal might become one of the important tools, especially for smaller organisation, to easily visualise their data. I was wondering though whether it would be possible to include results in the NaVi viewer. 

Another non -related question: Do the widgets automatically update when registry is updated?

**Comment by Jaspermid** [comment]
@notshi I don;t see any results. Are we clear what we mean by results

To me a result is for example the number of children helped, or the number of participants in a certain training. Is that information you see?

**Comment by notshi** [comment]
Ahh, it seems our wires were crossed and after looking at the pure XML of Cordaid data, I finally understand what you mean now.

As you know, due to the loose schema, there are a lot of variations in the activities published by one publisher compared to another.

When I designed SAVi, I made a point of only displaying the parts I fully understood; ie. the most used and popular <tags>. SAVi is also in her first iteration and we've not had the time or resource to better the current system.

I'll add <result> to the displayed data when I next get a chance to focus on SAVi. Till then, I'll leave this issue open.

**Comment by Mattdevinit** [comment]
@Jaspermid there are now Results showing on SaVi pages (where Results exist in the data), eg http://d-portal.org/ctrack.html?publisher=CA-3&tongue=eng#view=act&aid=CA-3-D000568001
does this cover what you were expecting/hoping for?

**Comment by Jaspermid** [comment]
Hi unfortunately not. This seems to be a comment field of some sorts (narrative information). The result I am talking about is the actual IATI result field. See http://aidstream.org/files/xml/partos_nl-activities.xml for an example 

Result would be Number of participants in a orkshop. For example. A larger ata file with results can be found at https://www.cordaid.org/media/medialibrary/2015/07/iati-activities.xml

**Comment by Mattdevinit** [comment]
For next month - include dates, target and actual data under results in Savi http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/result/

**Comment by notshi** [comment]
Test subject (wip, please ignore) - http://d-portal.org/ctrack.html?flava=original&rgba=mustard&publisher=NL-KVK-41160054#view=act&aid=NL-KVK-41160054-107216

**Comment by notshi** [comment]
@Mattdevinit Have added the new results in SAVi for the above example. Will need revision, depending on how it will be used. At the moment, it's just a basic layout to display data on the example page. It may look different with different data submitted.

**Comment by Mattdevinit** [comment]
@notshi thanks!  looks great - it would be good to check a handful of other publishers who have results data if poss, to see how that looks - as you say it may vary.  I guess some of these Savi pages will become quite long if there's a lot of results data, but as we are just displaying the data, I think that's ok here - otherwise we could think about showing 5 and hiding the rest or something.
And could we add a subheader (like 'Budget' and 'Transactions') for Results please

**Comment by notshi** [comment]
@Mattdevinit Yes, of course. Would you know which publishers? It would be good to have a few to focus on.

I found, through researching, a few below.

1. http://d-portal.org/ctrack.html?publisher=NL-KVK-27248417&tongue=eng#view=act&aid=NL-KVK-27248417-2250
2. http://d-portal.org/ctrack.html?search=reinforcing%20the%20round%208#view=act&aid=47045-AFG-011-G12-T
3. http://d-portal.org/ctrack.html?publisher=NL-KVK-51018586&tongue=eng#view=act&aid=NL-KVK-51018586-0001
4. http://d-portal.org/ctrack.html?search=unchs#view=act&aid=41120-180

As you can see, the results do vary as will the resulting layouts.

Where would those subheaders for Results be?

**Comment by Mattdevinit** [comment]
@Jaspermid there's a couple of minor tweaks to make, but is this what you wanted?  eg http://d-portal.org/ctrack.html?publisher=NL-KVK-41160054&tongue=eng#view=act&aid=NL-KVK-41160054-110430

**Comment by Mattdevinit** [comment]
@notshi subheader for 'Results' to look same as the headers for 'Budget' and 'Transactions' on the Savi pages, and to appear at top of Results information (at end of list of transactions) please

**Comment by notshi** [comment]
@Mattdevinit Result header is now live.

**Comment by Mattdevinit** [comment]
thanks @notshi (picky picky, could it be Results plural please/sorry!!)

**Comment by notshi** [comment]
Result was used as it's the actual attribute (just like Budget and Transaction). Also, there may be one result displayed, depending on the data published.

**Comment by Mattdevinit** [comment]
That makes sense, thanks.  I suppose from a data perspective there's multiple individual instances (of transactions or results) which is why in the schema/xml it's singular, but from a user perspective on savi pages we are showing multiple instances usually - on that basis I'd still go with plural (in fact for both results and transactions) on these pages, but not a big deal especially if it's taking it direct from the data

**Comment by notshi** [comment]
Thanks, @Mattdevinit  Will change them to plural then. Should we also change Budget to Budgets and Recipient Country to Recipient Countries for consistency?

**Comment by Mattdevinit** [comment]
@notshi reckon recipient country will more often than not singular so could keep that one, and yes to budgets please

**Comment by notshi** [comment]
@Mattdevinit Plurals are now live.
