### ISSUE TITLE
Showing commitments (where no disbursements and expenditure)

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#224]
There's been ongoing conversations for a while with some publishers about use of Commitments in their IATI data.  It's been agreed (by the tech team) that some organisations (mainly Development Finance Institutions) will/can ONLY publish Commitments, not Disbursements or Expenditure...and so we need to show the Commitments for those particular organisations.  

The simplest way to do it at the moment would be to show all Commitments for any publisher not publishing any Disbursements and/or Expenditures.  Do you have an idea how easy/time consuming it might be to do this?  (it would help in showing Canada's data, and an increasing number of private sector orgs who don't/won't publish D or E).  

There may be more complexities further down the line with this (but it's not something we can avoid and will improve the data in d-portal) but this seems like the simplest way forward for now?

**Comment by xriss** [comment]
Can I start by saying that I think it would be better if they published data in a special way, rather than us dealing with it as an exception? :)

What I think would be the "best" way to handle this would be to flag the publishers and then when we import their data we add a fake Disbursement which is just a copy of their Commitments. So data turns up in tables etc without any other change, as we know we will never get any better data.

This is also something simple that they could easily do with their published data, a simple duplication of Commitments, rather than us having a special case for some publishers.

**Comment by Mattdevinit** [comment]
Yes, absolutely!  That feedback will be made!

Ok, that sounds like a good solution - thanks.  I'll get the list of relevant orgs and forward on, so we can get going.

**Comment by notshi** [comment]
Any updates on this, @Mattdevinit ?

**Comment by Mattdevinit** [comment]
just waiting to see if funding is agreed for this and a couple of other small features

**Comment by notshi** [comment]
Thanks, Matt!
