### ISSUE TITLE
Hierarchies - how to show them

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#232]
Increasing numbers of publishers are using hierarchies within their data, and this often means that transactions are on secondary levels of the hierarchy (and depending on how we deal with these, there's the potential to show internal transactions instead of external ones)  .I think one fairly simple way to make sure we are getting the right transactions is to only take transactions at the lowest hierarchy level for each publisher (eg 1 if they don't publish hierarchies, or 2 if they publish hierearchies at two levels, etc).  This would also mean that where we currently don't see some transactions for a few publishers, as they are hidden at lower hierarchy levels, they would then show in d-portal.  So, a couple of quick questions...

Do we do anything with hierarchies at the moment?
If not, would this (showing transactions at lowest hierarchy level) be a problem to do?

Thanks

**Comment by caprenter** [comment]
The dashboard has some information about how it handles hierarchy in some of it's calculations:
Start here: http://dashboard.iatistandard.org/forwardlooking.html#h_narrative

However in assessing whether or not something is at the 'lowest hierarchy' this assumes (I think) that you know about all activities a publisher publishes (otherwise how do you determine it is the lowest level?). I'm guessing this could be a problem for applications that use aggregated data (like D-Portal?)

I think the dashboard is designed to work with a single publisher's data at one time, so assessing this is then possible.

We should have some documentation on this in the Standard - but darned if I can find it!

**Comment by stevieflow** [comment]
I guess the issue is - what about those publishers that publish transactions at multiple hierarchies - does that then mean data loss?

I took a quick look at three data files from three different publishers

(waring - links lead to CSV files)

datastore.iatistandard.org/api/1/access/activity.csv?registry-dataset=undp-afg
datastore.iatistandard.org/api/1/access/activity.csv?registry-dataset=dfid-af
datastore.iatistandard.org/api/1/access/activity.csv?registry-dataset=sida-af

In these cases, there are no transactions at hierarchy one level.  BUT - that was just a test, and doesnt answer the question Im afraid

The related issue is around instances where a budget might be published at one hierarchy, but not at a lower one.... as d-portal also uses ``budget`` data

**Comment by notshi** [comment]
Closing this due to age or lack of activity.
