### ISSUE TITLE
SAVi query not working

### ISSUE THREAD

**Issue by MichaelMedley** [devinit/D-Portal#263]
Looking at the introduction to SAVi at 
http://d-portal.org/about.html:
and clicking on one of the sample queries
http://d-portal.org/q.xml?from=act,sector,country&country=bd&sector_percent_not_null
I get an inappropriate result (a list of projects from many parts of the world, not just Bangladesh).

By the way, if SAVi queries DO generally work, shouldn't there be more detailed and specific guidance in how to construct them?

**Comment by notshi** [comment]
Thanks for bringing this to our attention, will have a look at this.

When the sample queries were put in, they were mainly for internal testing and quick links as proof of Q working.

This also means that the examples are currently not updated as we've had a lot changes since then (26 June 2014 - https://github.com/devinit/D-Portal/commit/dd5f0a87f12ac6d7d67956f706268cc52660aae5)

We're currently very limited in dev time for d-portal (https://github.com/devinit/D-Portal/issues/261#issuecomment-104653740) but it's good to know that Q is being looked at so hopefully  we'll have some dev time to work on this.

**Comment by notshi** [comment]
The sample query raised should now be working.

http://d-portal.org/q.xml?from=act,sector,country&country_code=bd&sector_percent_not_null
(country=bd should have been country_code=bd).

**Comment by MichaelMedley** [comment]
Thanks. Yes, the result now looks the right kind of thing.
