### ISSUE TITLE
Map on Ukraine page is not centred on Ukraine

### ISSUE THREAD

**Issue by Bjwebb** [devinit/D-Portal#287]
Ukraine page: http://d-portal.org/ctrack.html?country=UA&tongue=eng#view=main

Not sure if this is specific to my browser/machine confiuration, so here's a screenshot:
![d-portal-no-ukraine](https://cloud.githubusercontent.com/assets/634/10111953/74ae370e-63cf-11e5-85bc-19d9b1dce029.png)

**Comment by notshi** [comment]
Hi @Bjwebb!

The map center position is the average of all the positions in the activity data so this highlights the quality of data being published about Ukraine.

We decided against hardcoding central positions so the map can display any data instead of specific to one country; ie. listing multiple countries etc. Also, we wanted to encourage better data being published.

**Comment by notshi** [comment]
Actually, scratch that. Looks like recipient country is broken. Will take a look further.

**Comment by notshi** [comment]
Thanks, @Bjwebb. This is now fixed.
