### ISSUE TITLE
Using forever and watchify

### ISSUE THREAD

**Issue by bezunakarmi** [devinit/D-Portal#299]
Everytime I make changes in the code I have to rebuild the app and if any exception/error is caught, the server goes down and needs to restart it. So is there any way that I can use Forever and watchify (npm packages) in the project.

**Comment by xriss** [comment]
Forever can be used on the command line if you wish to, this is a node app so can just be started with forever instead of node.

Same with watchify, which of course is a trivial replacement of the browserify build step.

Both of these are just small changes to how you build or how you run the app. We try and keep build steps as simple and explicit as possible with no more dependencies than is absolutely necessary.

Note. We don't use forever on the live server as we keep the server up with scripts to check if the server is actually responding to requests or not, something forever does not do. It is very easy for a node server to lock up in ways beyond simple exceptions that forever will not protect you from.
