### ISSUE TITLE
Reduced no. of 3 digit codes in Search

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#359]
http://d-portal.org/ctrack.html#view=search Yohanna raised the issue that the list under 'Sector Category' is currently a lot shorter than the list of 3 digit codes compared to here http://iatistandard.org/201/codelists/SectorCategory/ @xriss @notshi could you check if we can re-instate them all please?  I checked the 5 digit codes under Sector dropdown and looks like they are all populated ok

**Comment by xriss** [comment]
Hi matt,

All the codes we use are still the CLv2 ones, not just the sector codes, all of them.

Should we bump  from CLv2 to CLv3 across the board?

**Comment by Mattdevinit** [comment]
Agreed to remove the aggregation currently used, to include full current list of 3 digit sector codes http://iatistandard.org/201/codelists/SectorCategory/

**Comment by notshi** [comment]
@Mattdevinit Thanks - this is now live on d-portal.org

By the way, this will change how d-portal reports sectors. Using our old grouping, we were simplifying the number of categories displayed specifically for CRS comparison.

http://d-portal.org/ctrack.html?search&publisher=GB-GOV-1#view=sectors

Applying this new change means CRS is slowly lowering in importance so this small change has a big impact on d-portal's original direction - is this ok?

There might be some layout issues due to the inconsistencies of cases (capitalised, uppercase) in the names of the sectors.

![cases](https://cloud.githubusercontent.com/assets/1515961/24368548/bcfe9cac-1318-11e7-9fd8-3f6ff8ddafec.png)
As seen on http://iatistandard.org/202/codelists/SectorCategory/ (version 2.02)

I don't think we should fix this but rather leave it to IATI as it is a consistency issue in the data level; ie. pick a case - all upper or capitalised, please.

**Comment by notshi** [comment]
Looks like the IATI Sector codes and categories might be incomplete - it does not list the full DAC Sector codes and categories found on http://www.oecd.org/dac/stats/dacandcrscodelists.htm
![dac_sectors](https://cloud.githubusercontent.com/assets/1515961/24398519/a987c502-13a1-11e7-9468-c4a88fce1a90.png)
*Fig. 1 -  Latest code update is dated March 2017*

We've noticed activities that report correct DAC 5 digit sector codes that do not correspond to the IATI list of DAC 5 digit sector codes.

![23210_0](https://cloud.githubusercontent.com/assets/1515961/24399019/529216ce-13a3-11e7-83a3-ec183f451772.png)
*Fig. 2 - [This activity](http://d-portal.org/ctrack.html?country=AF&tongue=eng#view=act&aid=CA-3-A033776003) reports to sector 23210*

![23210_1](https://cloud.githubusercontent.com/assets/1515961/24399024/55924cae-13a3-11e7-83a5-c5593c7b9b16.png)
*Fig. 3 - DAC Sector 23210 corresponds to Energy generation, renewable sources – multiple technologies*

![23210_2](https://cloud.githubusercontent.com/assets/1515961/24399026/5793b1dc-13a3-11e7-803f-2f3012d70cad.png)
*Fig. 4 - IAT's list of [DAC 5 Digit Sector](http://iatistandard.org/202/codelists/Sector/) skips code 23210*

![sector_bad](https://cloud.githubusercontent.com/assets/1515961/24398699/567fe366-13a2-11e7-925e-2b843852664c.png)
*Fig. 5 - These sectors currently show up on d-portal like so*

We will convert those sectors to show their DAC 3 digit numbers instead so we should update the "About data" text accordingly.

**Comment by notshi** [comment]
**Update:** Missing IATI DAC 5 are now converted to sector codes on d-portal ([see link](http://d-portal.org/ctrack.html?country=AF&tongue=eng#view=sectors)).
