### ISSUE TITLE
Add 'Status' dropdown to filters (replacing the 'Donor' dropdown)

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#364]
Add 'Status' dropdown (default is 'Total' if a filter not selected from this dropdown) - options to select 
Active
Ended
Planned
Total
This dropdown filter will replace the 'Donor' filter which overlaps with the 'Publishers' dropdown and has not proved as useful/clear to users

**Comment by notshi** [comment]
Should we be using http://iatistandard.org/202/codelists/ActivityStatus/ instead?

d-portal uses date ranges and specific rules to get our own categories ([link](http://d-portal.org/faq.html#tech4))

**Comment by notshi** [comment]
Reason for using the IATI codelist instead:

The current search filters were originally fitted for d-portal functions but have slowly been updated to follow the IATI standards (ie. donor, sector) as it was confusing for users.

We should maintain consistency in the search filters. In keeping with this, the dropdown will be renamed, "Activity Status".

Also, since we will be updating the search function to include the summary boxes and search results on the same page, it would serve a different purpose.
