### ISSUE TITLE
Apostrophe doesn't display properly on activity list page

### ISSUE THREAD

**Issue by Bjwebb** [devinit/D-Portal#371]
http://d-portal.org/ctrack.html?search&country=YE&publisher=GB-CHC-1043843#view=list_activities

![image](https://cloud.githubusercontent.com/assets/634/24419945/f4ff2060-13e8-11e7-8c22-f64392e9ee12.png)

**Comment by notshi** [comment]
Thanks @Bjwebb - that looks like a bizarre html entity that's not getting escaped. Will work out at which point the escaping is broken.

Hopefully it hasn't imported the file with the wrong encoding.

**Comment by notshi** [comment]
Upon closer inspection - http://preview.iatistandard.org/index.php?url=http%3A//109.123.121.248/csviati/static/2016-10-27/1477577831.13.xml (assuming this is the right dataset in the registry):

Viewing the xml file - http://109.123.121.248/csviati/static/2016-10-27/1477577831.13.xml
![women](https://cloud.githubusercontent.com/assets/1515961/24456329/987f12e4-148a-11e7-8824-57b260ee790a.png)
There appears to be encoding issues.

**Comment by notshi** [comment]
Hi @Bjwebb,

We think the encoding issue stems from the source: ([link](http://preview.iatistandard.org/index.php?url=http%3A//109.123.121.248/csviati/static/2016-10-27/1477577831.13.xml))

![encoding](https://cloud.githubusercontent.com/assets/1515961/24651537/14d4bebc-1926-11e7-8c2d-2950e3416293.png)

The apostrophe should sort itself out on the activity list page once the source is fixed by the publisher.

**Comment by Bjwebb** [comment]
Yes, looks like a problem in the source file. I think what threw me off is that the apostrophe displays fine on the activity page for that activity - http://d-portal.org/ctrack.html?search&country=YE&publisher=GB-CHC-1043843#view=act&aid=GB-CHC-1043843-DutchMFA-F011

**Comment by notshi** [comment]
Yeah, that threw me off too. What's happening here is the browser applying fixes to the page so instead of displaying as UTF-8, it has spotted the actual character encoding and has fixed it.

Magic browser reasons has decided to fix it for this page but not the previous one.

The bigger issue here is another IATI standard problem - they shouldn't be allowing non UTF-8 encoding anywhere in the schema.

**Comment by notshi** [comment]
This activity no longer exists (or has been renamed) but will create a new issue should similar issues crop up.
