### ISSUE TITLE
Recipient country maps not starting on recipient country

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#395]
eg Bangladesh initially shows India http://d-portal.org/ctrack.html?search&country=BD#view=main
Jamaica shows West Africa http://d-portal.org/ctrack.html?search&country=JM#view=main 
etc - seems same for most countries

**Comment by xriss** [comment]
I've looked at this, the problem is in the data, currently we just center the map on the middle of the data provided. This is so that the map works with publishers or any filter rather than just a specified country. Clicking through from the heatmap to the main map view will show up these other locations.

There are a lot of activities where they say they are 100% in a country but then list locations all over the place.

EG:

http://d-portal.org/q.xml?aid=US-GOV-1-BD-AID-OAA-C-14-00067

says it is 100% BD but then gives locations all over.

I think we can pick a better weighted center as it is obviously mostly in the right place will give it a try and see if that helps.

**Comment by xriss** [comment]
This is now weighted better for the heat map and mostly hits the right country but we are still being pulled away due to locations reported all over the world EG for Afghanistan

http://d-portal.org/ctrack.html?country=AF&tongue=eng#view=map&lat=32&lng=64&zoom=2

**Comment by notshi** [comment]
Hi @Mattdevinit - this is due to the recent publishing of mostly USA-GOV data that is publishing random locations (lat, long) that are all over the world instead of the country listed in the activity.

2 ways of dealing:

1. Only show the country specific map in country views
  - This would mean having to find an authoritative and reliable data source for the locations (lat, long) of each country.

2. Ask USA-GOV to fix their data
  - Not sure why they have made this big change and what these locations mean. Could be the location of organisations involved in the project?

**Comment by notshi** [comment]
By the way, we do not suggest option 1 because our current method obvious exposes problematic data and works perfectly when the data is good.

If we weren't doing it like this, we doubt anyone would notice that USA-GOV has been publishing random locations in their activities.

**Comment by notshi** [comment]
Example - http://d-portal.org/q.html?aid=US-GOV-1-NG-AID-OAA-TO-10-00066

Recipient country is 100% Nigeria but there is a total 138 locations found within that single activity pointing to (lat,long) that are not in Nigeria.

This effects how we determine the map center since we depend on the published location (lat,long) data in the activity to calculate it.

**Comment by notshi** [comment]
By the way, there's also ```location-reach``` attached to these locations - http://iatistandard.org/202/codelists/GeographicLocationReach/

There are 13 instances of code '1' and 125 instances of code '2' in that particular activity.

Should we be ignoring any one of these codes? Or does it not matter?
