### ISSUE TITLE
Click thru from freetext search results

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#408]
Via : https://twitter.com/RupertSimons/status/910911814875172865

See http://d-portal.org/ctrack.html?search=Nambia#view=main

If I click on any graph, the resultant page doesnt seem to load any data

**Comment by notshi** [comment]
The graphs are showing data for **all** years but the resultant pages when clicked through are only showing specific years (2015-2017).

You can click on the arrows to cycle through the other years to see the rest of the data.

**Comment by stevieflow** [comment]
OK, understood, thanks @notshi 

I guess a variation on this (but development) would be to revert to a display on the click through that shows some numbers, using the appropriate time range.  Could be tricky...

FWIW, I do think the UX is tricky - from a graph that is *populated* through to list that (potentially) isn't.  Maybe an alert box could help ?

**Comment by notshi** [comment]
Reverting to a display that show some numbers isn't consistent with the rest of the site so I *might* make it more obvious that the graphs are showing specific years; ie. [year range under header](http://d-portal.org/ctrack.html?search=Nambia#view=countries&year=2015).

Again, the 'all years' chart was added because publishers were complaining that their graphs weren't being shown. We use CRS as a base of year ranges (current & previous 2 years) so if publishers have not provided recent data, they won't have graphs on their 'portals'.

Perhaps we should remove 'all years' as this could *solve* most of such discrepancy issues but it does come with a compromise.

We try very hard to treat all data equally on d-portal so exceptions for *bad* data is not acceptable.

**Comment by stevieflow** [comment]
Understood, thanks @notshi 

Maybe therefore it's to do with just giving the user some on screen clue:

> Maybe an alert box could help ?

"Don't see any data?  Try changing the years" (or similar)

This might be cheapest way to assist people, without making fundamental changes under-the-hood

**Comment by notshi** [comment]
Thanks, @stevieflow - think I'l do that for now and see how it goes. Hopefully it'll give us something to point to when people say this page is broken :}

**Comment by notshi** [comment]
Hi @stevieflow - this is now live on the site.

**Comment by stevieflow** [comment]
*thumpsup*
