### ISSUE TITLE
When there's an @activity-id at the participating-org element, create a link

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#413]
(I thought we had talked about this before, but cant find in closed or open tickets)

See: 

http://d-portal.org/q.html?aid=41119-CORE-PROGRAMME

For Participating Orgs we link to the `ref`` for each entity.  So, for Denmark the link is to:

http://d-portal.org/ctrack.html?publisher=DK-1#view=main

However, in this instance, the XML also includes ``activity-id`` in the participating-org:

`<participating-org ref="DK-1" role="1" type="10" activity-id="DK-1-37918">`

Hence, the link could be more precise, to:

http://d-portal.org/q.html?aid=DK-1-37918

This would be more acceptable, I think - it gives the user direct access to the relevant project

NB: it may sometimes be the case that the link will "not work" - but that's for people to discover / fix : it should not hold back this imho

**Comment by Akerman** [comment]
Good point! The instinctive user or two has complained of that before.
![image 4](https://user-images.githubusercontent.com/6977022/31731035-c5984b1c-b401-11e7-8cbc-237d844eee03.png)
![image 5](https://user-images.githubusercontent.com/6977022/31731041-cb501c6a-b401-11e7-9a83-93ef5b27e557.png)

**Comment by stevieflow** [comment]
Found the closed ticket -  @notshi said this was done: https://github.com/devinit/D-Portal/issues/331 ... ?

**Comment by notshi** [comment]
From the above, I understood the issue as:

Use ```@activity-id``` over ```@ref``` if available. 

Would users be confused when clicking on links under WHO'S INVOLVED to be be directed to another SAVi page instead of a publisher portal? Assuming the casual user (do we have this?) is unaware of the full meaning of the ```participating-org``` element.

Due to the above, we did https://github.com/devinit/D-Portal/issues/402.

It might be worth rewording, 'Who's Involved' to something more relevant seeing as how it wouldn't apply to the example provided. Or does it?

> The instinctive user or two has complained of that before.

These are two completely different sections and elements displayed in SAVi. @Akerman Could you elaborate more about the complaints? Would appreciate it!

It might also be worth re-looking at how this section is displayed in SAVi and how it can be improved to show what it should be showing to be of use to users.

**Comment by Akerman** [comment]
Better to link to activity-id, Steven is right. All users so far clicked on the title thinking they were going to the activity. Had to scroll way down to record 3000+ to get what they were looking for.

Great work Shi, I'm just echoing Steven's concern.

-Martin

**Comment by stevieflow** [comment]
Yes - I think having the *precise* link will always be best.  This is one concept that is important around IATI & traceability: that activities link with other activities.  It's too wide ranging to make links between organisations - even though that is obviously derived from the activity linkage

So yes, I would agree with 

> Use @activity-id over @ref if available.

Thanks!
