### ISSUE TITLE
When XML only presents an org @ref, and this @ref is a publisher, utilise the name

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#416]
Take a look at this:

http://d-portal.org/q.html?aid=NL-KVK-41198677-AFGO_FUND-NL-1-PPR-27552

![codes](https://user-images.githubusercontent.com/1209944/31860116-45b821d8-b70d-11e7-804a-02a1fe3bd5ff.png)

The XML is such:
```

<participating-org ref="NL-KVK-41198677" role="2" type="21"/>
<participating-org ref="XM-DAC-7" role="1" type="10"/>
<participating-org ref="NL-KVK-41198677" role="4" type="21"/>
```
Hence, as the XML lacks a name for the organisation, d-portal only displays the code.  This is understandable, but not super useful for the end user. 

I understand that d-portal hosts it's own lookup of references for ``reporting-org`` identifiers.  This is where the name for the publisher page is derived from.

I would therefore propose that in instances where:

> when a org name is missing, but an organisation reference matches a stored publisher reference, then use name

This could cover the following main instances

``participating-org``
``transaction/receiver-org``
``transaction/provider-org``

**Comment by notshi** [comment]
Thanks, @stevieflow - This has quite a few layers.

We've tried to keep d-portal to _show what we have_ and display the data as is - to show the gaps, if you will; ie. in this case - if there isn't a name, show what is reported. However, there seems to be an increasing user need to go beyond that, as seen with the example provided.

For 2.02, the ```<narrative>``` element was introduced and suddenly all data with previous version became harder to support.

According to [the dashboard](http://dashboard.iatistandard.org/versions.html), **430** publishers are still using legacy versions or a combination of.  
This is currently more than the **362** publishers that have adopted 2.02.

This meant, we were now faced with the increasing challenge (dilemma) of creating an 'average' model so that SAVi views were more or less consistent (not too horrible to look at). We've managed so far but there are always edge cases and elements overlooked.

Currently, for ```participating-org```, we are doing these things:

1. Wrap data within elements with ```<narrative>```.
2. If there is text within ```participating-org```, leave it as it is.
3. Otherwise fill it with ```@ref``` or ```@activity-id``` if the element is empty, but use [```@activity-id``` over ```@ref```](https://github.com/devinit/D-Portal/issues/413#issuecomment-337868468) if available.
4. We also turn ```@ref``` or ```@activity-id``` into links.

For the proposed change, we will have to add these new steps:

1. If ```@ref``` is available, do a [lookup and use the publisher name](https://github.com/devinit/D-Portal/blob/master/dstore/json/iati_codes.json#L1593) and replace it with the converted text.
2. If ```@ref``` lookup is unsuccessful, just use the reported ```@ref``` raw text.

The steps above should, hopefully, also be applicable to ```transaction/receiver-org``` and ```transaction/provider-org```.

**Comment by notshi** [comment]
This will also affect ```planned-disbursement``` when ```receiver-org``` and ```provider-org``` elements get displayed.

**Comment by notshi** [comment]
@stevieflow - This change is now live on d-portal.

Please post errors or discrepancies below if you see them, thanks.

**Comment by stevieflow** [comment]
This is really helpful, thanks @notshi - I've added a post on Discuss for the wider community: https://discuss.iatistandard.org/t/data-use-observation-a-reference-for-an-organisation-alone-is-not-enough/1091/

**Comment by notshi** [comment]
That's great! Thanks, @stevieflow :}
