### ISSUE TITLE
Orgs not showing on homepage

### ISSUE THREAD

**Issue by Mattdevinit** [devinit/D-Portal#421]
@xriss @notshi there's only 2 orgs showing on d-portal at the moment.  Apparently the Registry was showing no activities or Datasets for a while just after midnight GMT https://github.com/ViderumGlobal/ckanext-iati/issues/112 in case this is linked

![1st nov - 2 orgs showing](https://user-images.githubusercontent.com/3502991/32271294-32f625cc-bef1-11e7-8f60-797b769abfa0.PNG)

**Comment by notshi** [comment]
Hi @Mattdevinit - yes, this is linked.

d-portal depends on the Registry to provide the data - this decision was to allow publishers to 'unpublish' files. Therefore, if there are no files in the Registry, we delete appropriately.

And since import from the Registry at midnight, the unfortunate timing has left us in this state.

We are now restarting import and it will slowly fill up again.

**Comment by Mattdevinit** [comment]
thanks @notshi, makes sense!

**Comment by notshi** [comment]
Import seems complete. d-portal is now back to schedule.

Have removed the _bug_ label as the system is working as designed.

We might set an arbitrary minimum limit of 1000 files and if the Registry dips below that, we won't un-publish anything.

You may witness the [dip in the graphs](https://xriss.github.io/D-Portal-Logs/) to highlight this moment for posterity.
