### ISSUE TITLE
Display the "progress bar" on activity page

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#423]
The progress bar for an activity is show on the listing (only for [active projects](http://d-portal.org/ctrack.html?search&country=TZ&sector_group=311#view=list_activities) I think #424 ?):

![list](https://user-images.githubusercontent.com/1209944/32404167-af9f84bc-c142-11e7-8eb0-1a0d5698a60f.png)

It would be useful to replicate (and maybe enlarge?) this on the actual activity page, especially as we often faced with a long list of transactions

**Comment by notshi** [comment]
The SAVi pages (single activity view) are completely different from all the other pages on d-portal.

SAVi pages are literally the raw IATI XML visualised using CSS.

The data is not processed at all - all we do is sort the order of the elements to display the page in a more legible way; ie. simple.

Due to this, things such as displaying a progress bar, sorting the transaction (etc.) tables and adding spreadsheet functionality to this page means a complete redesign of SAVi.

The 'plugin' idea was meant to be this redesign.

**Comment by notshi** [comment]
I'm going to close this since we now have graphs on activity pages which are more accurate than the single bar.
