### ISSUE TITLE
Progress bar for financials only shows on "all" lists

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#424]
I only see the progress bar on pages for "all" projects:

http://d-portal.org/ctrack.html?search&country=TZ&sector_group=311#view=list_activities

![list](https://user-images.githubusercontent.com/1209944/32404189-0574030e-c143-11e7-93b9-ddc916dc9a30.png)

But not on the listing of active projects on a search page:
http://d-portal.org/ctrack.html?search&country=TZ&sector_group=311#view=main

![active](https://user-images.githubusercontent.com/1209944/32404206-48e84d8e-c143-11e7-8873-10647e8f68d0.png)

Or the lists for active / closed projects

Is there a reason for that?

**Comment by notshi** [comment]
Yes - the active / closed projects are based on dates; ie. we use the dates to calculate their status since the 'activity status' element seems unreliable. Due to this, we only show the dates.

All projects include all the status; ie. active, closed, planned etc. Since the 'total projects' view is not focused on dates, we don't show it.

However, this is the first time we've had feedback on these pages so we'll look into what can be done.

**Comment by notshi** [comment]
From above, the new change will include both dates and 'progress bar' for all table views; ie. an additional column will be added to these tables where they are missing.

The views to apply this change to includes (new column):

1. Active projects (add progress bar)
2. Ended projects (add progress bar)
3. Planned projects (add progress bar)
4. Other projects (add progress bar)
5. Total projects (add date)
6. Main page tables (add progress bar)

**Comment by notshi** [comment]
The changes are now live on d-portal.

These views are also updated for donor and sector activities table (linked from the donor/sector tables following the graphs).

**Comment by notshi** [comment]
There's quite a fair number of changes so there _may_ be errors - appreciate it if any is spotted!
