### ISSUE TITLE
Close the feedback loop! Help data users contact publishers directly

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#437]
At the moment, this bar on d-portal links to support@iatistandard.org (a mailbox administered by the secretariat):

![screen shot 2017-11-24 at 17 32 37](https://user-images.githubusercontent.com/464193/33220043-8e071800-d13d-11e7-9820-7c31e15c906e.png)

However, if there are data errors, I would imagine it would be more efficient to close the feedback loop, and allow data users to contact publishers directly?

The IATI registry metadata includes a contact email address(es) for a publisher, as well as a contact email address for each dataset. Perhaps it would be better for d-portal to instead expose an email address for the publisher, so that data users can contact data publishers directly.

Note that as part of the standard, each activity may include [`contact-info`](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/contact-info/). However, my impression is this contact may not be the right person to talk to about data issues (though I could be wrong about this! If anyone can clarify, please do!)

Note that this is blocked until ViderumGlobal/ckanext-iati#71 is resolved, since there are still issues with publisher email addresses.

**Comment by YohannaLoucheur** [comment]
Sounds like an excellent suggestion. 

Regarding contact info, I know some organizations provide specific contact points for each/specific activities, but others (majority?) provide a single point of contact - who should be able to direct feedback or questions to the appropriate place (eg IT or project officer).

**Comment by bill-anderson** [comment]
I agree this is a good idea. From our current reading of the new European [data protection rules ](https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/) this would need to be a generic single point of contact otherwise the onus would be on the portal (in addition to the original publisher) to get the consent of specific contacts.

**Comment by PetyaKangalova** [comment]
@andylolz Thanks again for adding your suggestion in here. I agree with what has been said so far and Bill's point that feedback should be directed to

> to a generic single point of contact

which is the publisher_contact_email in the IATI Registry metadata.

Because of the different types of questions that we receive from d-portal users I suggest the below amendment:

**If you have any queries relating to the data itself, which is owned by the publisher, please contact** **XXXX** _(in here there should be a script to either pick the publisher email directly from the contact field of the Registry metadata, making sure it is being refreshed often to pick up updates in emails, OR add a  link to the publisher's IATI Registry page, where users can identify the email)_

**If you have any queries about how the data is shown in d-portal, or how up to date the data is, please see the FAQs or contact the IATI support helpdesk support@iatistandard.org**

As Andy said this is blocked until [ViderumGlobal/ckanext-iati#71](https://github.com/ViderumGlobal/ckanext-iati/issues/71) is resolved. I will update once the issue has been resolved.

**Comment by markbrough** [comment]
@bill-anderson re the processing of (publicly disclosed) personal data. I understand you're saying that if an organisation publishes the name of the relevant individual in `contact-info` then you would have to get permission from that individual to show that (already published) information?

This is a super interesting question and seems pretty important for the rest of the IATI community and others building tools on the back of open data -- is there any analysis on this you could point to? I found a pretty limited discussion of the implications of the GDPR for open data / transparency in general, but [this discussion seems to suggest](https://discuss.okfn.org/t/gdpr-vs-part-of-open-data/6254) that the public interest exemption ([Art. 6](https://gdpr-info.eu/art-6-gdpr/)) would mean no change for reprocessing of open data (see also [Art. 85](https://gdpr-info.eu/art-85-gdpr/)). I guess this is has pretty broad application, e.g. OpenSpending / FarmSubsidy / OpenCorporates so would be great if there were some research in this area. 

@johnadamsDFID -- wonder if DFID / UK gov have had any discussions about implications of GDPR for publishing open data? @timgdavies similarly have there been any discussions of this around publishing / using personal data in OpenContracting?

**Comment by bill-anderson** [comment]
@markbrough we are currently seeking legal advice. Will keep  you posted.

Our understanding currently is that for the account data held on the registry we will  definitely need consent to hold personal email addresses as this is 'our' database.

The case of the datastore or portal is less clear, but it can be interpreted that we have 'processed' the data and must therefore seek consent.

**Comment by notshi** [comment]
Many thanks, all, for your invaluable inputs.

We've recently added the [Registry link](#411) to d-portal so @PetyaKangalova's suggestion is now live on d-portal.

Do let me know if you want the text or information changed.

**Comment by YohannaLoucheur** [comment]
I just tested the new feature. Clicking on the new link took me to the general publishers page - all 600+ of them. Finding the publisher requires the user to remember who the publisher was (which may not be all that easy, if you've been checking several projects at once) and scroll for ever through the page, since there isn't a search function. 

Could we provide a link to the publisher's page on the Registry instead of the full list of publishers? This should be feasible based on the Activity ID (says the non-techie :-) ). 

Also, pet peeve of mine perhaps, but I think clicking on the link should open a new tab rather than leave (without warning) D-Portal. 

Cheers

**Comment by notshi** [comment]
Thanks, @YohannaLoucheur - could you say which link you clicked on?

The only time we send people to the general publishers page is when we can't be more specific; ie. when you do a search on d-portal and it includes multiple publishers.

In fact, the only time this feature works is when you are looking at a specific publisher portal - unless it's United States whose data is currently structured in a strange way.

You can still get to the Registry page by clicking on the 'VIEW IATI REGISTRY dataset' link found on every SAVi page.

![reg](https://user-images.githubusercontent.com/1515961/37545678-b92c4d4e-2961-11e8-91e8-763629a96a62.png)

And thank you for spotting the issue about links in tabs - in this instance, it should definitely open a new tab. This fix is now live.

**Comment by YohannaLoucheur** [comment]
"The only time we send people to the general publishers page is when we can't be more specific; ie. when you do a search on d-portal and it includes multiple publishers."

Then the new link does not work as expected. I did a search with CA-3 and Afghanistan, so there was only 1 publisher, yet I was taken to the general publishers page when I clicked on the new link (I am talking about the new link to ask a question about the data, of course). This is the project I tested.
http://www.d-portal.org/ctrack.html?search&country=AF&publisher=CA-3#view=act&aid=CA-3-S065210001

**Comment by YohannaLoucheur** [comment]
PS thank you for fixing the "new tab"!

**Comment by ClaudiaSchwegmann** [comment]
Hi @notshi 
I have tried the feature of accessing the publisher page directly from the activity opened in D-Portal. 
For some activities clicking on the link If you have any queries relating to the data itself, which is owned by the publisher, please contact them here.works. Though the publisher page does not open in a new page, instead I leave D-Portal. 
For other projects it does not work. Instead, I get to the registry page where I can select a publisher. For example, this one here:
http://www.d-portal.org/ctrack.html?country_code=CM#view=act&aid=XI-IATI-EC_DEVCO-2019%2F407-663 by the EU or this one http://www.d-portal.org/ctrack.html?country_code=CM#view=act&aid=CH-4-2017007459 by the Swiss Dev Cooperation.

**Comment by ClaudiaSchwegmann** [comment]
Hi @notshi I have tried the feature of accessing the publisher page directly from the activity opened in D-Portal. 
For some activities clicking on the link **_

> If you have any queries relating to the data itself, which is owned by the publisher, please contact them here_**. works. Though the publisher page does not open in a new page, instead I leave D-Portal. 
For other projects it does not work. Instead I get to the registry page where I can select a publisher. For example, this one here:
http://www.d-portal.org/ctrack.html?country_code=CM#view=act&aid=XI-IATI-EC_DEVCO-2019%2F407-663 by the EU or this one http://www.d-portal.org/ctrack.html?country_code=CM#view=act&aid=CH-4-2017007459 by the Swiss Dev Cooperation.

**Comment by ClaudiaSchwegmann** [comment]
Hi @notshi 
I have tried the feature of accessing the publisher page directly from the activity opened in D-Portal. For some activities clicking on the link works. Though the publisher page does not open in a new page, instead I leave D-Portal. 

For other projects it does not work. Instead I get to the registry page where I can select a publisher. For example, this one here:
http://www.d-portal.org/ctrack.html?country_code=CM#view=act&aid=XI-IATI-EC_DEVCO-2019%2F407-663 by the EU or this one http://www.d-portal.org/ctrack.html?country_code=CM#view=act&aid=CH-4-2017007459 by the Swiss Dev Cooperation.

**Comment by notshi** [comment]
Thank you, @ClaudiaSchwegmann for testing and raising this.

It won't work on those pages because they are country pages and not directly associated with a single publisher. We should remove that link for non-publisher pages.

And thanks for letting us know that the link does not open in a new page, that should also be fixed.

However, some publishers already do publish contact emails on each activity, ([eg](http://www.d-portal.org/ctrack.html?country_code=CM#view=act&aid=XI-IATI-EC_DEVCO-2015%2F366-870)).

![Screenshot-20200504115448-464x161](https://user-images.githubusercontent.com/1515961/80959159-22023100-8dfe-11ea-9fbd-5d9ebc829b0c.png)

Maybe we could put that at the top of the activity page with more information like 'Please contact this publisher ... etc'.

**Comment by notshi** [comment]
Closed due to age.
