### ISSUE TITLE
bmz and millenniumchallenge data missing from d-portal

### ISSUE THREAD

**Issue by andylolz** [devinit/D-Portal#447]
Lots of registry activities appear to be missing from d-portal. For instance:

 * [MCC only have 21 activities on d-portal](http://d-portal.org/ctrack.html?search&publisher=US-18#view=main). However, [the activity counts on the registry](https://iatiregistry.org/publisher/millenniumchallenge) suggest the number should be much higher.
 * Similarly, [the German Ministry for Economic Cooperation and Development only have 39 activities on d-portal](http://d-portal.org/ctrack.html?search&publisher=DE-1#view=main). Again, [the activity counts on the registry](https://iatiregistry.org/publisher/bmz) currently total over 6,000

**Comment by xriss** [comment]
What seems to be the problem here is that these activities used to be in a singe file that has been split into 2 and it looks like my attempts to log when an activity was last updated is getting upset and both files are failing on import.

So the activities have moved from one file to another and the code that deals with the same activity id getting published in multiple files is getting confused.

I think this is now fixed and things should be back in an hour or two after a full import completes.

**Comment by andylolz** [comment]
Wow BRILLIANT – thanks @xriss!

**Comment by notshi** [comment]
Thanks for spotting this, @andylolz - the portals should now be populated with the expected activity count.

Do get in touch if that is still not the case!
