### ISSUE TITLE
Search by recipient countries

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#458]
Please can we have the full list of recipient countries showing in the drop down list on d-portal. Not just those that align with the current OECD DAC CRS.

Many thanks,

Amy

**Comment by andylolz** [comment]
> the full list of recipient countries

I guess there are a couple of ways to decide on this list.

It could match this: http://iatistandard.org/203/codelists/Country/

But that codelist is marked as incomplete, so there will be recipient countries that aren’t included.

It could be derived from the data, excluding country codes that aren’t on the IATI country codelist and aren’t in the XA-XZ range.

**Comment by k8hughes** [comment]
What shows as available in the search is the current OECD DAC CRS as that was what d-portal was initially designed to do.

However you are actually able to view any country by changing the URL to include their 2-letter code.  - For example to view Russia: http://d-portal.org/ctrack.html?search&country=RU#view=main

The ones that are in the drop down list have design work done on the country specific pages, the background images and the flags are added.  
We don't currently have the budget to expand the country list to include everything with this same front end design component.

**Comment by andylolz** [comment]
This issue was just raised in Riza’s TAG 2018 talk, so flagging again here. In his case, the example was [Singapore](http://d-portal.org/ctrack.html?search&country=SG#view=main).

I appreciate adding flags / background images would be a lot of work (the reason given for closing this). Personally, I think it looks fine with the default background and no flag, [as shown here](http://d-portal.org/ctrack.html?search&country=SG#view=main). I’d rather have the option of seeing this data (without hacking a URL) than have the background image / flags.

**Comment by notshi** [comment]
@amy-silcock @andylolz All countries are now listed in the drop down list.

There might be issues with countries that are not recipient countries (?) in there.
Should probably add to the FAQ that countries with no flags are not CRS recipients.

**Comment by andylolz** [comment]
Brilliant – thanks for sorting this.
