### ISSUE TITLE
Please add Sectors to Location CSV Download

### ISSUE THREAD

**Issue by AndieVaughn** [devinit/D-Portal#480]
The recently added csv download for location information is a great addition, but it would be immensely helpful to users to include sector information in additional columns.  Can sector data be added to the download?

**Comment by AriaGrab** [comment]
I agree with this, being able to have a better understanding of the work that is actually happening by location in a downloadable format would be super helpful.

**Comment by JamesCoe** [comment]
+1. This would be helpful when trying to download the data and build a landscape.

**Comment by k8hughes** [comment]
Could we have the IATI identifier at the same time when you work on this feature?

**Comment by xriss** [comment]
Have added sector but not sure this is a good idea as it is an unexpected addition that explodes out the data, repeating lines for each sector listed in the activity. It feels like it should be a specific query via a different page rather than the default data provided from the map page.

Which goes back to us needing to add a designed interface for all data downloads https://github.com/devinit/D-Portal/issues/409 so you can specify exactly what you want.

The IATI identifier is already there, it was converted into a d-portal URL by prepending it with "http://d-portal.org/q.html?aid=" after this issue was raised requesting it be made easier to get to more information about a listed activity - https://github.com/devinit/D-Portal/issues/370

Again this is the sort of thing that should be addressed as options in a data download interface rather than trying to fit all requests into default actions. I think we should do this separately as a proper chunk of dev work as this seems to be a feature request that seems to be in demand. It would be good to spend some time devoted to making this available on the landing page.

**Comment by notshi** [comment]
Sectors has been added to CSV downloads.

We will close this issue for now but we are looking at expanding this into further work to support #409, after which we will then look into changing the csv download columns to reflect the map page.
