### ISSUE TITLE
Changing ordered lists to unordered

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#486]
In any activity page, the list of ``participating-org`` is provided as an ordered list - eg:

![d-portal 2](https://user-images.githubusercontent.com/1209944/45414237-ce643200-b672-11e8-96bd-2c00f8cd1e95.png)

I have observed that for some people, this ordering *implies* importance (1 being the most important, downwards).  

This is not the intention of the publisher - the order in the XML is not indicative of anything

To avoid confusion, I think it would be best to change this to an unordered list.  In can be in the same *order*, but without the numbers!

**Comment by notshi** [comment]
Thanks, @stevieflow - this is interesting to know. Could you link me to this activity, please?

The only reason this became an ordered list was so it was easier for users to see how many organisations made up the list, especially in long lists like the one above. Otherwise, the list can get very unwieldy and hard to read (always our priority over any political reasoning).

I'm also unsure if an unordered list will solve anything as it will still ultimately be displayed as a list; publishers might still find issue being at the top/bottom.

Maybe we could order this list alphabetically instead?

**Comment by notshi** [comment]
Have removed the list numbers for now.

**Comment by notshi** [comment]
> Who's implementing (1)
A
Who's funding (13)
A
B
C
Who's extending (1)
A
Who's accountable (2)
A
B

This was an approach we thought of but decided against it when we had data that looked like this - http://d-portal.org/ctrack.html?publisher=US-GOV-1#view=act&aid=US-GOV-1-AID-524-A-15-00002 where each section could repeat the same data.

Might the above appear in variations of data like http://d-portal.org/q.html?aid=XM-DAC-41121-2018-GLOBALPROG ? And which should come first - [the standard says funding](http://reference.iatistandard.org/202/codelists/OrganisationRole/) but will publishers see that as another ranking order? Does being at the top of the funding list suggest being the top funder?

In the end, it became a numbered list (this was done before the count of orgs was shown) grouped in org roles. Might change the colours of the different roles to make that clearer.

**Comment by YohannaLoucheur** [comment]
> This was an approach we thought of but decided against it when we had data that looked like this - http://d-portal.org/ctrack.html?publisher=US-GOV-1#view=act&aid=US-GOV-1-AID-524-A-15-00002 where each section could repeat the same data.

Not sure what the issue is in this example - the same data is already repeated three times, with a different tag. 

Some more user feedback for consideration: 
With a long list like the 2nd example, I almost wish to have tabs, enabling me to focus on the role I'm most interested in that day (and not having to scroll down such a long list to get to the next section).  

Colours could indeed help to distinguish the different roles, for those of us who can see colours. But we already  have yellow and white, so it could become a bit much...

**Comment by notshi** [comment]
The issue with that example is the list getting longer and longer if the 2nd example does the same thing and repeats for each of those orgs. This echoes the same concern you raise with not having to scroll down so much. We also have to take consideration with short lists. 

Particularly, it would be good to know why this list is important and what it is used for in regards to looking at an activity.

The solution might be a combination of all these things so might need to stew on this further. Thank you for the feedback, everyone.

**Comment by stevieflow** [comment]
Thanks @YohannaLoucheur and @notshi for additional discussion

For me, the change from an ordered to unordered list fixes the original post / issue report I had.  Further iterations and discussions are great, but just wanted to flag that I appreciate the quick and effective response
