### ISSUE TITLE
Query about search function on d-portal

### ISSUE THREAD

**Issue by ChristaKernick** [devinit/D-Portal#507]
Is it now the case that if you search for a particular word (e.g. from a project title), the  search results will include an EXACT match only?
For example, if you search on "CSSP", you will not get project titles with "CSSP2" in your search results?
 
A few weeks ago I searched on just part of a word, “cit”, and I got a whole list of records with names including “cit” (e.g. city, citizen, citizenship). By the same principle I would expect to see "CSSP2" listed among project titles containing "CSSP", but this does not happen.

Has something changed?

**Comment by notshi** [comment]
Hi @ChristaKernick - many thanks for your patience.

Because of the way the dictionary works in the database, there are specific ways a freetext search is handled. As per your example, "cit" can be part of a word in the English dictionary; ie. city, citizen, citizenship.

However, CSSP is not a combination of letters that is found in the dictionary as part of a word so "CSSP2" will not be listed.

We have now updated the freetext search and you should be able to search with these following operators:

|Operator   |Meaning   |
|---|---|
|:*   |wildcard   |
|&#124;   |or   |
|&   |and   |
|!   |not   |

For example, [here is a search](http://d-portal.org/ctrack.html?text_search=CSSP%3A%2a#view=list_activities) for ```CSSP:*``` which also includes CSSP2.

Using ```:*``` allows for a wildcard search which means listing results that includes CSSP as the start of a word.

**Comment by notshi** [comment]
Closing this as resolved.
