### ISSUE TITLE
Incorrect End Date Showing

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [devinit/D-Portal#515]
Hi Team,

Louis Berger Group have raised an issue whereby the wrong end date is showing for their activity.

Please see the following screenshots:

**Raw XML**

![image](https://user-images.githubusercontent.com/46994072/54838955-baecf000-4cc1-11e9-97d3-a273e6561368.png)

**D-Portal**

![image](https://user-images.githubusercontent.com/46994072/54838979-cd672980-4cc1-11e9-8399-100cdfaefdf6.png)

Curiously, the correct date (22/07/15) is showing for me.

Please can you look into/advise why this might be showing incorrectly to the user?

Many thanks,
Josh

**Comment by notshi** [comment]
Thanks, @JoshStanleyDevInit - could you send me a link to the activity? That would be much appreciated, thanks.

**Comment by JoshStanleyDevInit** [comment]
Hi Shi,

Apologies, I meant to link it in my first comment!

Here you go: http://d-portal.org/ctrack.html?publisher=US-EIN-22-1754524#view=main

Josh

**Comment by notshi** [comment]
Hi @JoshStanleyDevInit the correct date is showing for me too.

Could you ask if they could clear their browser cache? It could be that they are looking at a cached version of the data on their browser so it's showing them an old date that was published.

**Comment by JoshStanleyDevInit** [comment]
Hi @notshi,

They said that they have cleared the cache and viewed the page on several different devices and are still getting the same!

**Comment by notshi** [comment]
Thanks, @JoshStanleyDevInit.

Can we confirm they are looking at http://d-portal.org/ctrack.html?publisher=US-EIN-22-1754524#view=main and not on a local site? Just trying to cover all bases.

**Comment by JoshStanleyDevInit** [comment]
Hi @notshi,

Yes that's the URL they are using - they provided that to me because I wanted to make sure that we were definitely looking at the same page!

Thanks for looking into this.

Josh

**Comment by notshi** [comment]
Thanks, @JoshStanleyDevInit - really sorry we can't seem to reproduce the bug and with very little information, we don't know how to approach fixing this.

I wonder if all the devices they are looking at is from within the same network and that's where the problem is stemming from.

When they look at the SAVi page of that activity ([http://d-portal.org/ctrack.html?publisher=US-EIN-22-1754524#view=act&aid=US-EIN-22-1754524%20-2042885](http://d-portal.org/ctrack.html?publisher=US-EIN-22-1754524#view=act&aid=US-EIN-22-1754524%20-2042885)), do they see the following?

![Screenshot-20190326135125-1099x420](https://user-images.githubusercontent.com/1515961/55002536-b3359000-4fce-11e9-950d-03fa2557f7a1.png)
![Screenshot-20190326135154-1006x685](https://user-images.githubusercontent.com/1515961/55002545-b9c40780-4fce-11e9-84f2-2536d095ad99.png)

**Comment by JoshStanleyDevInit** [comment]
Hi Shi,

The publisher has decided not to pursue this for now so I will close this issue.

Thanks for looking into it!

Josh
