### ISSUE TITLE
Issue with headline graphs when filtering only by sector/sector category

### ISSUE THREAD

**Issue by JoshStanleyDevInit** [devinit/D-Portal#541]
UNIDO have been in touch to highlight an issue with the 'Where does the money come from?' graph when filtering only by sector or sector category (not by a specific publisher).

See screenshots:

![image](https://user-images.githubusercontent.com/46994072/70445193-1438c180-1a93-11ea-856d-83a3ed4334e6.png)
![image](https://user-images.githubusercontent.com/46994072/70445206-1733b200-1a93-11ea-9e63-ef7d27eafc95.png)
![image](https://user-images.githubusercontent.com/46994072/70445213-1ac73900-1a93-11ea-8d34-bf60b5e69a50.png)

**Comment by notshi** [comment]
Thanks, @JoshStanleyDevInit - this looks like another bug that was added when the new search was implemented. The sectors have to be treated differently as they could be included in the transactions unlike the other search filters, which are at activity level.

This should now be fixed. - please let me know otherwise.

**Comment by JoshStanleyDevInit** [comment]
Looks good! Thanks for the speedy response @notshi!
