### ISSUE TITLE
Activities without an end date are not classed as Active

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#545]
See: 

http://d-portal.org/ctrack.html?reporting_ref=US-EIN-95-3202116#view=main

Here; all 63 activities are in the active box:

![d-portal (3)](https://user-images.githubusercontent.com/1209944/73440132-a7ca9800-4348-11ea-844d-85ee718c6c47.png)

However, d-portal does not list them in the active projects list, further down the page:

![d-portal (4)](https://user-images.githubusercontent.com/1209944/73440208-c6309380-4348-11ea-9205-9a064f4a6713.png)

I think the issue is that all these activities only have a start date.  

![d-portal (5)](https://user-images.githubusercontent.com/1209944/73440417-26273a00-4349-11ea-9120-1154746b2846.png)

However, these are "ongoing" activities, so have neither a planned or actual end date.  To the publisher the are therefore active

1 - please can we clarify how this page on d-port includes them in the active stats box, but not the list?
2 - does d-portal need both a start and end date?   As evidenced, that isn't always relevent/possible

Thanks

**Comment by notshi** [comment]
1. For projects to be listed in that list, we need the end dates because that's how we sort them; ie. projects with an end date closest to the date today will be listed first.

2. D-portal does not need both start and end date - as shown, these projects are considered 'Active'. However, since they lack an end date, they will not show up on that particular list as this requires an end date.

This is a list showing 5 most recent projects that are active so we need the end dates in order to find those projects. The label of that list used to say, "Active projects ending soon" but it has since been changed and there is still the title, "Recent first" at the top right of the list.

Technically, we are querying for 5 projects that are about to end. If no end dates are listed, the result of this query is 0 projects. We could then ask for 5 random projects to make up the numbers but this would involve another query before displaying data on the page, thus adding to load time and will not provide any useful information as this project will randomly change since there is no order to them.

In the [FAQ](http://d-portal.org/faq.html), under Technical no. 8, we state:
![Screenshot-20200130192936-781x200](https://user-images.githubusercontent.com/1515961/73483147-e25b2180-4396-11ea-9743-8db35c9ab6bb.png)
I've since updated the general FAQ about projects with missing end date.

**Comment by notshi** [comment]
Should probably change the title to:

Activities without end date are not shown on the list of projects ending soon

**Comment by stevieflow** [comment]
Thanks for the clarification @notshi 

> The label of that list used to say, "Active projects ending soon" but it has since been changed 

Yeah, as we have two places on the same page for "Active projects", it seems counter intuitive to have different criterion for them

> Should probably change the title to:

(did you miss something?)

> Activities without end date are not shown on the list of projects ending soon

That would be helpful - thanks.  I think the immediate "data quality issues" text is something that troubles users, particularly when they feel there is no data quality issue to be had!

**Comment by notshi** [comment]
> (did you miss something?)
Should probably have been more explicit! I meant the title of this issue, ie. activities without an end date are already classed as Active, just not listed on the front page section below.

I've changed the list title to 'Projects ending soon' - that should hopefully be less confusing.

As for the 'data quality issues' - this could be a legitimate problem (end date earlier than start date, etc) but in this case, it could also apply to activities without end dates. I think what we'll do is remove the sections when there aren't any activities with end dates.

In fact, we will also apply this to the map so there are no empty sections when there is no data to show.

**Comment by notshi** [comment]
Will close this as the section now has a less confusing title and will not show if there is no data.
