### ISSUE TITLE
Results data - GAIN ?

### ISSUE THREAD

**Issue by stevieflow** [devinit/D-Portal#561]
I noticed the addition of a field called GAIN in the results data - eg:

http://d-portal.org/q.html?aid=US-EIN-45-2796201-0068

![d-portal org q html aid US-EIN-45-2796201-0068](https://user-images.githubusercontent.com/1209944/80389404-f1247800-88a2-11ea-84c3-fc569d6c0831.png)

Please could you clarify where this comes from?  As it is not explicitly referenced in the IATI standard, this should be documented / explained.

Also - it would be worth checking if this also works in relation to https://github.com/devinit/D-Portal/issues/547

**Comment by notshi** [comment]
Hi @stevieflow yes, this was previously the background colour that denotes a positive, negative or no changes to the actual element in indicators.

Gain is the ```actual``` expressed as a percentage from the ```baseline``` to the ```target``` and it's clamped from 0 - 100; so we never get 101 or -10. 

We are writing a blog post to explain this further but we are currently taking a break from the recent (massive) updates to the website so this will be done rsn.

**Comment by notshi** [comment]
@xriss to answer #547

**Comment by amy-silcock** [comment]
Please can we remove the 'gain' column from the activities page? It goes beyond what is in the standard.

**Comment by stevieflow** [comment]
> Please can we remove the 'gain' column from the activities page? It goes beyond what is in the standard.

I can understand this reaction, as that was the thought from my original post.  However, I think we have to also accept that d-portal (and all the other tools) that use IATI data do things that "go beyond what is in the standard"  For example, the data that informs the aggregation graphs of d-portal are not in the standard, not are the progress bars between a start date and end date.  A progress bar could easily be something like "45% complete" - which is not in the standard.

As @notshi points out, the concept of GAIN was already in d-portal (for about three years?), but just expressed through different colours.  With it now explicitly labelled, it does throw up interesting discussions, but I'm not convinced it should be immediately removed because it is not in the standard.  However, I also agree that is this is a specific label that is not documented for the user.

**Comment by JoshStanleyDevInit** [comment]
I agree that the "Gain" column should be removed, just because it feels like an extraneous addition.

It's fairly easy to work out the progress of Target vs Actual if required; I like the idea of just having the coloured circle as it gives a quick visual representation of how the indicator is performing.

**Comment by notshi** [comment]
Closing this as resolved.

**Comment by notshi** [comment]
Just FYI - This column was renamed as '**%**' in [this commit](https://github.com/devinit/D-Portal/commit/360f60a3628036d491c640bc213c97dc8da36996#diff-d6e44c44ea9a494dd2a3eeda39f151cdd6a2421aef2d42ebb9a3bbaa5dcc09be) and since then, the naming convention and display layout has become canonical as seen in these tools below.

https://aida.tools/activity/XM-OCHA-HPC8568-XM-DAC-7-PPR-4000002150/performance#
![Screenshot-20210701205418-1920x1056](https://user-images.githubusercontent.com/1515961/124185500-fab2fc80-dab2-11eb-96bf-bec07f7d76e8.png)

https://liberiaprojects.org/activities/329
![Screenshot-20210701205355-1920x1056](https://user-images.githubusercontent.com/1515961/124185502-fb4b9300-dab2-11eb-8fb6-6182ad7e2dc0.png)
