### ISSUE TITLE
Special characters (such as %) are not searchable in dPortal

### ISSUE THREAD

**Issue by AudreyIATI** [devinit/D-Portal#598]
[dportal_list_activities 2015 -2020 gender marked activities 2021-01-13v3.xlsx](https://github.com/devinit/D-Portal/files/5813638/dportal_list_activities.2015.-2020.gender.marked.activities.2021-01-13v3.xlsx)

Data user has raised the following issue with the IATI team via the Helpdesk: 
Some of the activities have ‘%’ in both the title and the link which make them un-unreadable for Vlook up and  un-searchable in d-portal. Is there a fix for this?

See attached file for example.

**Comment by notshi** [comment]
Thanks, @AudreyIATI for raising.

I'll respond here and the helpdesk with their query as there are a few points to touch on.

Original question:

> I have exported from d-portal all the IATI activities which have gender policy 1,2 and 0 marked. However some of the activities have ‘%’ in both the title and the link which make them un-unreadable for Vlook up and  un-searchable in d-portal. Is there a fix for this?

Regarding the % in titles, there is a character encoding bug with Excel that could be fixed by **importing** the csv instead of directly opening it in Excel. **You have to make sure that Excel is importing the file as UTF-8**.

This issue is also raised via the Datastore https://github.com/zimmerman-team/iati.cloud/issues/2416 
It also seems to be an existing and ongoing bug for Excel ([Link](https://stackoverflow.com/questions/155097/microsoft-excel-mangles-diacritics-in-csv-files#155176)).

Regarding the % in links, they have to be there because it is standard for URIs and browsers need these characters encoded to work properly.

We have, however, fixed the '%' for the ```iati-identifier``` column as it shouldn't be there.

Finally, the data user should be using the Datastore as a data source, not d-portal. Especially for large sets of data like this.

**Comment by notshi** [comment]
Closing this as discussions continued via the helpdesk.
