### ISSUE TITLE
IFIC provides 6 results, results loader many more

### ISSUE THREAD

**Issue by siemvaessen** [devinit/D-Portal#610]
See: https://d-portal.org/ctrack.html#view=search&text_search=IFIC [Trying to find this activity](https://d-portal.org/ctrack.html#view=act&aid=XI-IATI-EC_DEVCO-2019%2F41918%2F0)

And screenshot.
![Screenshot 2021-03-04 at 14 22 15](https://user-images.githubusercontent.com/961036/109970348-3b615b80-7cf5-11eb-8d27-d0035924fabe.png)

**Comment by notshi** [comment]
The search bar has autocomplete so what you are seeing are codelists you could be searching for.
However, if you press enter, it will perform the actual search hence you only get 6 activities / results.

The autocomplete is convenient when you want to pick, say for example, a sector filter by typing the sector name instead of choosing it from the filter drop down above.
