### ISSUE TITLE
KRW to USD currency conversion issue

### ISSUE THREAD

**Issue by andreaszenasidi** [devinit/D-Portal#611]
Data users raised a concern about unusually large funds reported by the Republic of Korea in d-portal. 

**1. Activity KR-GOV-051-2015010319737:** in the [XML](https://d-portal.org/q.xml?aid=KR-GOV-051-2015010319737) the Outgoing Commitment shows KRW 95,200,000 which is around USD 84,000, the same amount is shown on the d-portal activity [page](https://d-portal.org/ctrack.html?country_code=TM&reporting_ref=KR-GOV-010#view=act&aid=KR-GOV-051-2015010319737). However, on the [summary page](https://d-portal.org/ctrack.html?country_code=TM&reporting_ref=KR-GOV-010#view=list_activities), $136,621,230 of Outgoing Commitments are shown which is not the correct currency conversion. 

**2. Activity KR-GOV-051-2020010100045**: the [XML](https://d-portal.org/q.xml?aid=KR-GOV-051-2020010100045) reports KRW 7,140,000,000 which is around USD 6 million. The [summary page](https://d-portal.org/ctrack.html?country_code=MG&reporting_ref=KR-GOV-010#view=active) shows USD 10 billion.

**Comment by notshi** [comment]
Thanks for raising, @andreaszenasidi this could be related to https://github.com/devinit/D-Portal/issues/485 and/or https://github.com/devinit/D-Portal/issues/465 but we will need to investigate.

**Comment by notshi** [comment]
Hi @andreaszenasidi looks like the problem was down to unexpected commas in IMF data ([source](https://www.google.com/url?q=https://www.imf.org/external/np/fin/data/rms_mth.aspx?SelectDate%3D2004-01-01%26reportType%3DCVSDR%26tsvflag%3DY&sa=D&source=hangouts&ust=1615056947078000&usg=AFQjCNESz5wJ1Z_fvNh8zGNuNjNhoDFVZg)) and how we are parsing it.

```
Korean won	1,774.460000	1,783.760000	NA	1,773.200000	1,768.370000	1,772.260000	1,779.290000	1,765.480000	1,764.560000	1,761.220000	1,764.070000
```
It looks like IMF is reporting data with commas in other currencies as well; ie. Colombian peso, Indonesian rupiah and Iranian rial so this fix, when it is checked in, will deal with those as well.

**Comment by notshi** [comment]
Hi, @andreaszenasidi this fix is now live.

**Comment by andreaszenasidi** [comment]
@notshi many thanks for the quick fix!
