### ISSUE TITLE
Cells populating incorrectly in location data csv

### ISSUE THREAD

**Issue by sarahshamiso** [devinit/D-Portal#618]
Filtered for Liberia as Recipient Country and downloaded the csv with activities that are shown in the map.

http://d-portal.org/ctrack.html?country_code=LR#view=map&lat=6.42802750000077&lng=-9.429249500000001&zoom=5

The data is incorrectly populating in the downloaded file (see attached).

[dportal_map_activities_11 April 2021.xlsx](https://github.com/devinit/D-Portal/files/6292278/dportal_map_activities_11.April.2021.xlsx)

**Comment by notshi** [comment]
Sorry about that - Github automatically closes an issue when you do a commit referencing that issue.

**Comment by notshi** [comment]
Hi @sarahshamiso thanks for raising.

Looks like there is an unescaped newline that is causing the issue.

![Screenshot-20210412113559-897x201](https://user-images.githubusercontent.com/1515961/114381675-496f8b00-9b83-11eb-8ae0-0ce534b4ac0c.png)

Using [this activity](http://d-portal.org/q.html?aid=XM-DAC-41122-Liberia-2550/A0/07/007/001) as an example, you can see in the 'description' that the sentence is over two lines.

![Screenshot-20210412113749-683x144](https://user-images.githubusercontent.com/1515961/114381884-97848e80-9b83-11eb-9298-afb7f1bd4909.png)

That's due to a ```\n``` newline published in the data. You can download the csv from that page to see it.

![Screenshot-20210412114926-723x114](https://user-images.githubusercontent.com/1515961/114383182-2940cb80-9b85-11eb-9e55-5ce777759e88.png)

Will let you know when the bug is fixed.

**Comment by notshi** [comment]
Hi @sarahshamiso this fix is now live.

**Comment by sarahshamiso** [comment]
@notshi Fantastic -- thank you so much for looking into this and addressing it so quickly!
