### ISSUE TITLE
Including codelist names in CSV output

### ISSUE THREAD

**Issue by PetyaKangalova** [devinit/D-Portal#622]
Sharing here directly feedback from a user received via the IATI helpdesk. The user was not familiar with the sector codelist (which I  have now referenced them to) and thought there was an error in the CSV file. Ttheir request was if possible to add the name of the sector code in addition to the code.

![image](https://user-images.githubusercontent.com/24607542/121706618-b47b0680-cacd-11eb-8a89-b7d8259008a8.png)

![image](https://user-images.githubusercontent.com/24607542/121706770-d96f7980-cacd-11eb-875c-5ea3811176c9.png)

**Comment by notshi** [comment]
Hi @PetyaKangalova, this feature has been pushed live to the sector table page.

CSV downloads will now include the sector names in a new column next to the sector codelist.

We have also updated to using the [IATI NonEmbedded Codelists](https://iatistandard.org/en/iati-standard/203/codelists/sectorcategory/#sectorcategory) where it was previously [a curated csv](https://github.com/devinit/D-Portal/blob/master/dstore/csv/sector_category.csv) because we were asked to rename some of the sector groups. This is no longer necessary as it looks like the names have been updated since then (2018).

Do let us know if that's not the case.

**Comment by PetyaKangalova** [comment]
@notshi thank you so much! I just checked and looks great.

Yes, I can confirm that the [sector codelist](https://iatistandard.org/en/iati-standard/203/codelists/sectorcategory/#sectorcategory) from the IATI website should be used and this is the most up-to-date version. Happy for the issue to be closed.
