### ISSUE TITLE
Result indicator order in d-portal is incorrect

### ISSUE THREAD

**Issue by andreaszenasidi** [devinit/D-Portal#628]
Handicap International Federation is trying to understand why their Result Output indicator shows up in the wrong order in d-portal, even though in the IATI Registry XML file it's ordered correctly.

**D-portal activity:**  http://www.d-portal.org/ctrack.html?reporting_ref=FR-RCS-519655997#view=act&aid=FR-RCS-519655997-20200103
**Registry XML file:** https://aidstream.s3.us-west-2.amazonaws.com/xml/hi_fed-activities.xml
**Example of wrong order:** _Output 1.1 - Access to resources, infrastructures and livelihoods is improved_ should appear before _Output 1.2 - Risk of EO related death and injury is reduced_

**Comment by xriss** [comment]
Everything in SAVi (single activity view) gets sorted by something.

In this case, the results are primarily sorted by `@type` so they could be grouped together, then by the data content which in this case would have been a narrative in the indicators (**i**ndicator comes before **t**itle alphabetically, and that being the first difference).

I've added a forced sort on title/narrative so that fixes this issue and makes sense but generally the order that the data is published in is not going to change how things are displayed in SAVi.

**Comment by notshi** [comment]
We've also sorted `</indicator/title/narrative>` so the order of that will follow alphabetically.

It would be good to have some IATI guidance on how to use and visualise results data, specifically in the subject of ordering and grouping elements within elements, as result data can often be rather spaghetti in its nature and d-portal tries very hard to make sense of it.

**Comment by andreaszenasidi** [comment]
@notshi @xriss thanks both for looking into this and making the change! In terms of IATI guidance on ordering and grouping Results, we don't currently have one but it's definitely something to consider for the future!
