### ISSUE TITLE
Sector Vocab 12 not displaying

### ISSUE THREAD

**Issue by amy-silcock** [devinit/D-Portal#635]
UNHCR have noticed that the sector vocabulary 12 is not being displayed in d-portal. Their other reported sector vocabularies are:

For example this activity [XM-DAC-41121-2022-EUR-BELMCO](http://d-portal.org/ctrack.html#view=act&aid=XM-DAC-41121-2022-EUR-BELMCO)

Has sector vocabs, 1, 19, 99 and 98 displayed, but not 12.

![image](https://user-images.githubusercontent.com/27764077/145001751-57029ddb-7b03-46b4-935d-64d2065cb4d7.png)

**Comment by notshi** [comment]
Thanks, @amy-silcock - looks like [sector 12 was added in June](https://github.com/IATI/IATI-Codelists-NonEmbedded/commit/c8cd16acd04eca0920de6ed7182354a3bfe908a6) and since SAVi needs new vocabs to be added manually, we missed it.

Sector Vocab 12 has now been [added to SAVi](https://github.com/devinit/D-Portal/commit/64a5cb05610352acc7659e50eb828e62938e27a9) so should display. Do let me know if that's not the case.

**Comment by amy-silcock** [comment]
Thanks Shi, I confirm that sector vocab 12 is now displaying as expected.
